### ISSUE TITLE
Make install error

### ISSUE THREAD

**Issue by dragoshirnea** [alecsandruchirosca/SRD2019#1]
Eroare la executarea comenzii "make install" :

Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/share/Geant4-10.5.1/data/G4NDL4.5
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot make directory
  "/usr/local/share/Geant4-10.5.1/data/G4NDL4.5": No such file or directory

Makefile:73: recipe for target 'install' failed

**Comment by alecsandruchirosca** [comment]
Trebuie executat cu sudo. Am corectat si in fisierul README.

Multumesc
