### ISSUE TITLE
Make command SRD

### ISSUE THREAD

**Issue by dragoshirnea** [alecsandruchirosca/SRD2019#2]
In încercarea de a face un build manual, am întâmpinat următoarea problemă la executarea instrucțiunii ”make” :

dragos@linux-os:~/GEANT4/bin/SRD2019/build$ make
Scanning dependencies of target G4APP
[  8%] Building CXX object CMakeFiles/G4APP.dir/main.cpp.o
In file included from /home/dragos/GEANT4/bin/SRD2019/main.cpp:31:0:
/home/dragos/GEANT4/bin/SRD2019/include/DetectorConstruction.hh:7:10: fatal error: G4GDMLParser.hh: No such file or directory
 #include "G4GDMLParser.hh"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/G4APP.dir/build.make:62: recipe for target 'CMakeFiles/G4APP.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/G4APP.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:931: recipe for target 'CMakeFiles/G4APP.dir/all' failed
make[1]: *** [CMakeFiles/G4APP.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alecsandruchirosca** [comment]
Este cel putin ciudat, puteti sa-mi trimite-ti va rog output-ul instructiunii 
env | grep G4
Ce versiune de Geant folositi? Eu am instalat astazi o masina virtuala folosind instructiunile din README si nu am intampinat aceasta problema.

Noi nu folosim GDML in proiectul nostru deci puteti comenta include-ul respectiv dar nu cred ca de acolo este problema.

**Comment by dragoshirnea** [comment]
dragos@linux-os:~/GEANT4/bin/SRD2019/build$ env | grep G4
G4INCLDATA=/usr/local/share/Geant4-10.5.1/data/G4INCL1.0
G4LEVELGAMMADATA=/usr/local/share/Geant4-10.5.1/data/PhotonEvaporation5.3
G4RADIOACTIVEDATA=/usr/local/share/Geant4-10.5.1/data/RadioactiveDecay5.3
G4PIIDATA=/usr/local/share/Geant4-10.5.1/data/G4PII1.3
G4SAIDXSDATA=/usr/local/share/Geant4-10.5.1/data/G4SAIDDATA2.0
G4ABLADATA=/usr/local/share/Geant4-10.5.1/data/G4ABLA3.1
G4REALSURFACEDATA=/usr/local/share/Geant4-10.5.1/data/RealSurface2.1.1
G4NEUTRONHPDATA=/usr/local/share/Geant4-10.5.1/data/G4NDL4.5
G4PARTICLEXSDATA=/usr/local/share/Geant4-10.5.1/data/G4PARTICLEXS1.1
G4ENSDFSTATEDATA=/usr/local/share/Geant4-10.5.1/data/G4ENSDFSTATE2.2
G4LEDATA=/usr/local/share/Geant4-10.5.1/data/G4EMLOW7.7


Versiunea de GEANT este 4.10.05.p01

**Comment by alecsandruchirosca** [comment]
am modificat sursele pentru a scoate toate referintele la GDML.
Noua versiune ar trebui sa functioneze fara probleme.

**Comment by dragoshirnea** [comment]
dragos@linux-os:~/GEANT4/bin/SRD2019/BUILD_SRD2019$ make
Scanning dependencies of target G4APP
[  8%] Building CXX object CMakeFiles/G4APP.dir/main.cpp.o
[ 16%] Building CXX object CMakeFiles/G4APP.dir/src/ActionInitialization.cc.o
[ 25%] Building CXX object CMakeFiles/G4APP.dir/src/AnalysisManager.cc.o
[ 33%] Building CXX object CMakeFiles/G4APP.dir/src/DetectorConstruction.cc.o
[ 41%] Building CXX object CMakeFiles/G4APP.dir/src/PhysicsList.cc.o
[ 50%] Building CXX object CMakeFiles/G4APP.dir/src/PhysicsListMessenger.cc.o
[ 58%] Building CXX object CMakeFiles/G4APP.dir/src/PrimaryGeneratorAction.cc.o
[ 66%] Building CXX object CMakeFiles/G4APP.dir/src/RunAction.cc.o
[ 75%] Building CXX object CMakeFiles/G4APP.dir/src/SensitiveDetector.cc.o
[ 83%] Building CXX object CMakeFiles/G4APP.dir/src/SensitiveDetectorHit.cc.o
[ 91%] Building CXX object CMakeFiles/G4APP.dir/src/SteppingAction.cc.o
[100%] Linking CXX executable G4APP
[100%] Built target G4APP

A  funcționat după ce am comentat și #include "G4GDMLParser.hh" din src/DetectorConstruction.cc

**Comment by alecsandruchirosca** [comment]
ok, am comentati si eu codul inclusiv instantierea din fisierul header.
